### PR TITLE
Addition: Parsing Config Settings from a TOML file

### PR DESCRIPTION
**Pull request by Kannav02**
This pull request adds the feature that allows the user to specify the CLI arguments in a TOML config file and resolves issue #8 

Checklist 
- [x] Make the function to find and read the TOML file
- [x] Make the functionality to load and use the variables from the TOML while the CLI binary is being called
- [x] Documentation has been updated to reflect changes
- [x] Example TOML file has been added

### CODE REVIEW

**Comment by arilloid** [comment]
Hello @Kannav02,

Thank you for your contribution! I have fetched and tested your logic, the base functionality is good, but there are a couple of minor issues that I wanted to highlight. 

- I think the implementation of `find_toml()` function can be changed to search for the `.toml` file in users' home directory (e. g. "C:\Users\username") instead of the current directory, so they won't have to worry about putting the config file in their current working directory every time that want to use the tool. 

- `find_toml()` can also be changed to look for a specific file instead of any config file ending with `.toml` (in case users have other `.toml` files in their home directory).

- Using standard Windows path single backslashes (`\`) when specifying the location of the context file causes parsing errors, as `tomllib` seems to treat those as escape characters. So Windows users would have to specify the paths with double backslashes (e. g. `context = "examples\\commented.py"` vs. `context = "examples\commented.py")`. Just something that would be helpful to mention in the tool's docs.

**Comment by Kannav02** [comment]
sure! i will make implement these changes, thanks for the feedback

**Comment by Kannav02** [comment]
Hey @arilloid 
I've made the changes that you had asked for

thank you!

**Comment by arilloid** [comment]
Thank you for your contribution! 
I have tested and merged the changes.

**Pull request merged**
